docs/setup.md
Includes the answers from @lastzero in #3. Minor reformats to the docker script.
=> Adds #3 answers to setup questions

docs/faq.md
Few changes for my blogpost as well, I am going to improve the blogpost tomorrow with more information about user mapping which can be tricky.
=> Add info about database directory mapping

docs/faq.md
Apologies, b and d are almost the same :)
=> Correct option for database dir mapping

docs/developer-guide/setup-fedora.md, docs/developer-guide/setup.md
I'm not sure if y'all are opposed to setup instructions for folks which leverage your project without docker, but here they are if y'all want them ; )
=> feat(setup): added fedora setup/build instructions

docs/developer-guide/setup.md
Otherwise, checkout will work but you can't build the project since there are windows CRLFs in the file
=> Add a hint that you have to disable git's autocrlf.

docs/user-guide/user-faq.md
Issue: https://github.com/photoprism/photoprism/issues/493 showed there is some missing information in the docs. I have attempted to expand here.
=> Add information about sidecar files

docs/getting-started/proxies/advanced-nginx-proxy-setup.md, mkdocs.yml
I've created an advanced guide on how to setup nginx with proper certificates, HTTP/2 and optional http basic auth security.
=> Advanced nginx setup with HTTPS, HTTP/2 and Certificates

docs/getting-started/kubernetes.md
Touching up the Kubernetes documentation a little.
=> K8s docs update

docs/user-guide/settings/advanced.md
I know this page has recently been worked on and I hope my changes aren't too interfering. Feel free to select or cherry-pick a subset of changes if you prefer.
On reading the Advanced Settings section of the PhotoPrism app, there were still areas which weren't clear to me, in particular around how the size limits worked. I have slightly restructured the corresponding documentation to clarify this.
=> Update Advanced Settings documentation

docs/user-guide/use-cases/dropbox.md, mkdocs.yml
This is the setup I've been using to store and index my photos into PhotoPrism.
I think having articles like this help with SEO as well as being useful.
If Dropbox is too specific, I could create a broader article instead covering Dropbox and alternatives (like [Amazon Elastic File System](https://aws.amazon.com/efs/), Google Drive).
=> Describe Dropbox use case

docs/developer-guide/library/heif.md
It looked to me like this had been completed
=> Remove link to closed issue and clarify Todo

docs/developer-guide/library/heif.md
See https://github.com/photoprism/photoprism/issues/668#issuecomment-756913345
=> Clarify TODO for creating heif thumbnails

README.md, docs/developer-guide/documentation.md, docs/developer-guide/library/thumbnails.md, docs/user-guide/settings/places.md, docs/user-guide/settings/sync.md, docs/user-guide/sync/webdav.md
- I removed a couple of empty pages.
- I replaced duplicate content with links to the original instead.
- I cross-referenced the different webdav/sync docs as to avoid confusion
=> De duplicate various docs pages

docs/user-guide/organize/search.md
See https://github.com/photoprism/photoprism/discussions/1082#discussioncomment-391904
=> Filters: Explain wildcard

docs/getting-started/advanced/transcoding.md
Also minor tweaks to readability
Ref: https://github.com/photoprism/photoprism-docs/issues/61
=> Add devices info to transcoding doc

docs/user-guide/sync/sync-phone.md
A good and free alternative for smb and android users
=> add an free android alternative

docs/user-guide/organize/delete.md
Added to the documentation that this is also a setting that must be enabled.
=> Add note about delete setting.

docs/developer-guide/setup.md
exceptionally nitpicky corrections
=> minor grammatical edits

docs/user-guide/organize/edit.md
Short note about the Geolocation plugin
=> Short note about the Geolocation plugin

docs/getting-started/config-options.md
`PHOTOPRISM_DISABLE_FFMPEG` also disable video thumbnails
=> extend description of PHOTOPRISM_DISABLE_FFMPEG

docs/developer-guide/ui/rest-api.md
As discussed in https://gitter.im/browseyourlife/community?at=614853565b92082de1b003be
=> Add example with authentication

docs/developer-guide/ui/infinite-scrolling.md, mkdocs.yml
Adds developer docs for things around the topic of infinite scrolling and virtualization.
Related issues: https://github.com/photoprism/photoprism/issues/2258
Related PRs: https://github.com/photoprism/photoprism/pull/2292, https://github.com/heikomat/photoprism/pull/1
This not yet proofread. I'm also somewhat unsure about it being to detailed, as it got quite long while a lot of other ui-docs are really not that long.
=> add infinite-scrolling docs

docs/user-guide/advanced/restore.md
I've added an hint that the login credentials of the previous database will also be restored.
=> Login credentials from restored database

docs/getting-started/raspberry-pi.md
Aiming to solve one part of [this issue](https://github.com/photoprism/photoprism/issues/2275)
Added links to the PhotoPrismPi project
=> Adding PhotoPrismPi documentation references

docs/getting-started/troubleshooting/docker.md
as discussed in https://github.com/photoprism/photoprism/issues/2334#issuecomment-1200467339
=> Add troubleshooting guide when using `selinux`

docs/getting-started/advanced/transcoding.md
Includes docker compose additions and toolkit installation link.
=> Added instructions for Nvidia Container Toolkit

docs/getting-started/advanced/transcoding.md
Added required environment variables for the Nvidia Container Toolkit that I missed the first time around.
=> Updated Nvidia Container Toolkit docs

docs/getting-started/advanced/backups.md
Add backup instructions for sqlite as this doesn't currently work using `photoprism backup` command.
=> Update backups.md for sqlite

docs/getting-started/troubleshooting/docker.md
Since i had multiple reset with converting NEF file, i could increase the stability by changing the swap file and only use one worker.
=> add info for raspberry 4 with 4GB

docs/user-guide/settings/library.md
Changed settings parameter from "Estimates" to "Extrapolated Location".  Added note to raise awareness of common situations when this tool produces undesired results.
=> Clarifies description of Extrapolate Location

docs/getting-started/troubleshooting/windows.md
Add windows troubleshooting for larges files downloaded from photoprism via WebDAV.
https://github.com/photoprism/photoprism/discussions/3417
=> Getting Started: WebDAV Windows Error 0x800700DF

docs/getting-started/docker-compose.md, docs/getting-started/docker.md
add missing copy command to documentation
=> Docu add copy

docs/getting-started/troubleshooting/mariadb.md
Add link to MariaDB Docker Official Images FAQ.
=> Getting Started: Improve MariaDB troubleshooting guide

docs/getting-started/troubleshooting/performance.md
=> Getting started - MariaDB performance

docs/developer-guide/machine-learning/classification.md
=> docs: update github rules.yml reference

docs/getting-started/proxies/traefik.md
Clarification from https://github.com/photoprism/photoprism/discussions/4407
=> Add clarification for TLS use with Traefik

docs/user-guide/pwa.md
For make it easier for elderlies or tired folks like yours truly was.
Closes #190
=> Clarify which "dots-vertical" to press

docs/user-guide/sync/mobile-devices.md
Photosync has almost all transfer options under paid addons including webdav and smb
=> Update mobile-devices documentation to include paid addon
