photoprism/photoprism-docs

docs/setup.md
Closes #5 by adding a description with examples of how to find the cache folder inside the container and exposing to the outside via a second `--volume` parameter of a docker script. Includes on example based on test setup with a ZFS file system Ubuntu 18.04 LTS and two pools. See discussion at https://github.com/photoprism/photoprism/issues/178 . 
Separately, point out that there are currently no LXC builds for PhotoPrism.
=> Describe how to add separate cache file path

docs/getting-started/docker-compose.md
I've added a small tutorial on how to mount NFS shares directly with docker.
Guess the compose section is the best fit so far. Maybe even a new page?
=> add-section-for-external-storage-configuration

docs/developer-guide/tests.md, docs/getting-started/kubernetes.md
I'm not really familiar with MkDocs format specs, but this change solves the issue. The screenshot below is on the [Tests](https://docs.photoprism.org/developer-guide/tests/) page, but the [Kubernetes](https://docs.photoprism.org/getting-started/kubernetes/) has the same problem. I've tried to search over the codebase and only find those two broken pages.
**Before**:
**After**:
=> Fix Broken MkDocs List Format

docs/getting-started/docker-compose.md
Add one example so that people see different ways to mount directories.
=> docker-compose: add example with full path

docs/getting-started/config-options.md
High memory and CPU usage happen only if no thumbnails have been generated, see https://github.com/photoprism/photoprism/issues/413#issuecomment-660490025
=> Explain PHOTOPRISM_THUMB_UNCACHED

docs/getting-started/kubernetes.md
A few typos in the kubernetes deployment and changed image to refer to latest instead of a specific version
=> Fix typos in kubernetes example

docs/getting-started/portainer/synology.md
Add a newline after the code block, causing next paragraph to increment major step number instead of becoming another substep for step 4.
=> Fix outline numbering in Synology/Portainer doc

docs/developer-guide/setup.md
It would be useful to have the contributor's guide list the normal set of steps you'd run during development. `make all` builds more than would typically be desired. Normally a developer will build the frontend and backend separately
=> Describe how to build frontend in watch mode

docs/getting-started/advanced/backup.md, mkdocs.yml
As promised long ago, here is a short entry in the documentation on backing up pictures using photoprism.
I've also linked to the (ongoing) discussion for the more curious users.
=> Add backup docs

docs/getting-started/proxies/nginx.md
Show more details how to make the proxy actually employ SSL encryption. I should admit that I am by no means an NGINX wizard. This works for me and browsers are happy. Let's put the barrier to proper encryption as low as possible! :)
=> Add SSL to the NGINX proxy example configuration

docs/user-guide/settings/advanced.md
Explain how to use the different settings to view original images when it's possible to not view the thumbnails.
See https://github.com/photoprism/photoprism/issues/627#issuecomment-770302999
=> Show original images

docs/getting-started/proxies/SWAG.md, mkdocs.yml
Wrote documentation on using SWAG by linuxserver.io as a reverse proxy. It integrates ssl. 
Waiting on the linuxserver.io team to included the config.sample file in a future version. Will edit this documentation when completed.
=> adding swag documentation,easy to use reverse proxy

docs/getting-started/proxies/SWAG.md
Certificates of subdomains weren't trusted with www. now it is changed to 'wildcard'
=> Change docker-compose of SWAG

docs/getting-started/proxies/apache-2.md
It's unnecessary, and plain mod_proxy is much more performant than the rewrite engine.
=> Don't require mod_rewrite for Apache proxying

docs/getting-started/advanced/databases.md
This fixes https://github.com/photoprism/photoprism/issues/495
It adds the migrations from MariaDB to Sqlite and back in the advanced section under the topic of databases.
=> Add guide for database migrations

docs/user-guide/organize/search.md
Thanks for the commit 9690c28a8849ac252a290f99e9eacfad2ec5daa4 that added that.
Add another way that works too, and easier to read in my opinion, see https://github.com/photoprism/photoprism/issues/881#issuecomment-908389394
=> search: show another way to do an “and” query

docs/developer-guide/translations.md
Recently i noticed many translations were bad with non-correct meaning. After letting devs know, i figured out, after every frontend/backend update, they also update translations in all languages resulting in language errors by the translator. I think this note is pretty on point to warn contributors to check all translations in their language before every try of contributing.
Also added tip of the day for ease of use for contributors that met this issue.
=> Added note about checking translations

docs/user-guide/use-cases/google.md
Link to Google Takeout album import tool (https://github.com/inthreedee/photoprism-transfer-album) as requested in https://github.com/photoprism/photoprism/issues/869#issuecomment-1004102827
=> Add transfer albums section, link to community project

docs/developer-guide/translations-weblate.md
My dashboard doesn't show the Backend:
> ![image](https://user-images.githubusercontent.com/2071331/161585313-62483480-6ecd-4fe8-a2c2-2769928ca140.png)
Possible reason: I chose the French language and it's already 100% translated.
So I added a link in the doc to open the page directly.
=> weblate: add direct link to the Backend

docs/getting-started/proxies/nginx.md
Increase the max body size to 500 MB of an http request, since you may want to upload huge stuff via the upload GUI / webDAV
=> Increase max body size

docs/getting-started/troubleshooting/index.md
Just had the same problem as photoprism/photoprism#2412
Since no errors show up in the logs etc. it took me way too long to debug this. (And I only even noticed by accident, since there were just a few photos missing on a download of ~400)
Try to help anyone who might stumble upon this in the future by adding it to the troubleshooting checklist. Hopefully people will actually try that checklist, or at least Google will index this at some point and direct people there.
=> Troubleshooting: Add note regarding missing files in zip downloads

docs/user-guide/search/filters.md
This is a minor change to remove the literal backticks (`) that show up in the rendered documentation and make this part consistent with the other code quotes.
=> Remove backticks

docs/user-guide/settings/general.md
Fixes a tiny typo: `suite` -> `suit`
=> User Guide: fix typo in general.md

docs/getting-started/advanced/kubernetes.md
Annotation was outdated. See the official docs for the correct annotation name.
https://cert-manager.io/docs/usage/ingress/
=> Fix cert-manager annotation in example ingress

docs/getting-started/advanced/security-guide.md
As requested in https://github.com/photoprism/photoprism/issues/1987#issuecomment-1505851214, I've started a Docker Security Guide that includes recommendations for running services as a non-root user and getting passwords out of the container's environment.
=> Add docker security guide

docs/getting-started/docker-compose.md
highlighted and show example of mounting a volume with read-only flag.  added example for storage mount with write access since it's required (or highly recommended).
=> highlight the read-only mode and storage mounts

docs/getting-started/advanced/kubernetes.md
The kubernetes instructions had a few issues. Namely,
* `PHOTOPRISM_EXPORT_PATH` was being set, but this doesn't seem to have any effect (or at least this env var isn't documented anywhere else)
* `PHOTOPRISM_STORAGE_PATH` was not explicitly set, so it would default to `/photoprism/storage`, which would be in ephemeral storage (since that directory was not declared as a volume)
* `PHOTOPRISM_BACKUP_PATH` was similarly not set, so the directory would have been ephemeral.
In my experience, these problems (especially the unset `PHOTOPRISM_STORAGE_PATH` var) caused issues since it meant that photoprism was unable to store API keys on boot, preventing the activation of a membership.
=> Kubernetes: Update instructions to properly mount the storage path

docs/developer-guide/setup.md
- Update developer docs to add instructions for the Delve debugger based on https://github.com/photoprism/photoprism/pull/3555
=> Developer Guide: Add debug instructions for the backend Go code

docs/user-guide/settings/advanced.md
I presume
> The actual impression depends on how much information an image contains
is meant to be
> The actual **compression** depends on how much information an image contains
=> Advanced: fix 'impression' typo

docs/getting-started/troubleshooting/mariadb.md
mysqld isn't needed as part of command (and won't work from 11.0+).
Updating mysql.user cannot be done in 10.4+, was never a real mechanism, and from 10.4+ plugin authentication and passwords where accepted.
Setting password with ALTER USER (or SET PASSWORD) is all that is required.
=> Getting Started: Improve MariaDB troubleshooting guide  - passwords

docs/getting-started/advanced/transcoding.md
Clarify that MPEG4-AVC is not reencoded when resolution exceeds limit
=> Clarify MPEG4-AVC encoding docs

docs/getting-started/proxies/traefik.md
A [while ago](https://doc.traefik.io/traefik/migration/v2/#v2112), Traefik changed the default value of responding timeouts from none to 60 seconds. This breaks larger uploads, like videos.
To fix this, we have to specify the read timeout specifically in the HTTPS entrypoint config of Traefik.
=> Getting Started: Add responding timeout for Traefik
